/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Jframe;

import Jframe.Exception.OutOfRangeException;
import javax.swing.JOptionPane;


public class NumberGuessingGameWindow extends javax.swing.JFrame {

    private static final String EMPTY_STRING = "";
    private static final String MAIN_WINDOW_TITLE = "Guess The Number";
    private static final String STARTING_MESSAGE = "Please select your range of numbers!";
    private static final int LOWEST = NumberGuessingService.STARTING_MINIMUM_VALUE;
    private static final int HIGHEST = NumberGuessingService.STARTING_MAXIMUM_VALUE;
    
    
    private NumberGuessingService guessingService;
    
    /**
     * Creates new form NumberGuessingGame
     */
    public NumberGuessingGameWindow() {
        initComponents();
        setTitle(MAIN_WINDOW_TITLE);
        lblResultMsg.setText(EMPTY_STRING);
        spLowest.setValue(LOWEST);
        spHighest.setValue(HIGHEST);
        guessingService = new NumberGuessingService();
        updateRange();
        
        lblStartingMessage.setText(STARTING_MESSAGE);
        
        btnGuess.setEnabled(false);
        btnNewNumber.setEnabled(false);
        txtInputGuess.setEditable(false);
    }
    
    private void updateRange() {
        int minimumVal, maximumVal;
        minimumVal = (int)spLowest.getValue();
        maximumVal = (int)spHighest.getValue();
        guessingService.setRange(minimumVal, maximumVal);
        lblRange.setText("Guess a number between " + minimumVal
                + " and " + maximumVal + ".");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtInputGuess = new javax.swing.JTextField();
        btnGuess = new javax.swing.JButton();
        lblRange = new javax.swing.JLabel();
        lblInputGuess = new javax.swing.JLabel();
        lblResultMsg = new javax.swing.JLabel();
        spHighest = new javax.swing.JSpinner();
        spLowest = new javax.swing.JSpinner();
        lblHighest = new javax.swing.JLabel();
        lblLowest = new javax.swing.JLabel();
        btnNewNumber = new javax.swing.JButton();
        btnSetRange = new javax.swing.JButton();
        lblStartingMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 255));

        txtInputGuess.setText("0");
        txtInputGuess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInputGuessActionPerformed(evt);
            }
        });

        btnGuess.setText("Guess");
        btnGuess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuessActionPerformed(evt);
            }
        });

        lblRange.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRange.setText("Guess a number between 1 and 100.");

        lblInputGuess.setText("Your guess:");

        lblResultMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResultMsg.setText("You are correct!");

        lblHighest.setText("Highest");

        lblLowest.setText("Lowest");

        btnNewNumber.setText("New Number");
        btnNewNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewNumberActionPerformed(evt);
            }
        });

        btnSetRange.setText("Set Range");
        btnSetRange.setName("txtSetRange"); // NOI18N
        btnSetRange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetRangeActionPerformed(evt);
            }
        });

        lblStartingMessage.setText("Step 1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(lblLowest)
                            .addGap(7, 7, 7)
                            .addComponent(spLowest, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(52, 52, 52)
                            .addComponent(btnSetRange)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblHighest)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spHighest, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(lblResultMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnGuess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblInputGuess))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtInputGuess, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnNewNumber))))
                    .addComponent(lblRange, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(lblStartingMessage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblRange, lblResultMsg});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnGuess, btnNewNumber});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {spHighest, spLowest});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblStartingMessage)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblRange)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtInputGuess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblInputGuess))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuess)
                            .addComponent(btnNewNumber))
                        .addGap(18, 18, 18)
                        .addComponent(lblResultMsg))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spHighest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHighest))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spLowest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLowest))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSetRange)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuessActionPerformed
        
        final String WINDOW_TITLE = "Error";
        final String WRONG_FORMAT_MSG = "You must guess number.";
        final String TOO_LOW_MSG = "Too low! Try again.";
        final String TOO_HIGH_MSG = "Too high! Try again.";
        final String CORRECT_MSG = "You got it!";
        
       
        
        try {
            
            int guess = Integer.parseInt(txtInputGuess.getText());
            int difference = guessingService.checkGuess(guess);
        
            if (difference < 0) {
                lblResultMsg.setText(TOO_LOW_MSG);
            } else if (difference > 0) {
                lblResultMsg.setText(TOO_HIGH_MSG);
            } else { // difference == 0
                lblResultMsg.setText(CORRECT_MSG);
            }
            
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, WRONG_FORMAT_MSG, WINDOW_TITLE,
                    JOptionPane.ERROR_MESSAGE);
        } catch (OutOfRangeException ore) {
            JOptionPane.showMessageDialog(this,
                String.format("You must guess in the range %d to %d.",
                    guessingService.getMinimumVal(), guessingService.getMaximumVal()
                ),
                WINDOW_TITLE, JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnGuessActionPerformed

    private void txtInputGuessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInputGuessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInputGuessActionPerformed

    private void btnNewNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewNumberActionPerformed
        
        guessingService.newRandomNumber();
        lblResultMsg.setText(EMPTY_STRING);
        txtInputGuess.setText(EMPTY_STRING);
        spHighest.setValue(HIGHEST);
        lblStartingMessage.setText(STARTING_MESSAGE);
        btnGuess.setEnabled(false);
        btnNewNumber.setEnabled(false);
        txtInputGuess.setEditable(false);
        updateRange();
    }//GEN-LAST:event_btnNewNumberActionPerformed

    private void btnSetRangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetRangeActionPerformed

        lblStartingMessage.setText(EMPTY_STRING);
        
        btnGuess.setEnabled(true);
        btnNewNumber.setEnabled(true);
        txtInputGuess.setEditable(true);
        
        updateRange();
    }//GEN-LAST:event_btnSetRangeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuess;
    private javax.swing.JButton btnNewNumber;
    private javax.swing.JButton btnSetRange;
    private javax.swing.JLabel lblHighest;
    private javax.swing.JLabel lblInputGuess;
    private javax.swing.JLabel lblLowest;
    private javax.swing.JLabel lblRange;
    private javax.swing.JLabel lblResultMsg;
    private javax.swing.JLabel lblStartingMessage;
    private javax.swing.JSpinner spHighest;
    private javax.swing.JSpinner spLowest;
    private javax.swing.JTextField txtInputGuess;
    // End of variables declaration//GEN-END:variables
}
